global:
  name: consul
  datacenter: dc1
  acls:
    manageSystemACLs: true
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
server:
  replicas: 3
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
ui:
  enabled: true
  service:
    type: "NodePort"
connectInject:
  enabled: true
  default: false
  replicas: 3
  logLevel: "debug"
  k8sAllowNamespaces: ["*"]
  k8sDenyNamespaces: []
  metrics:
    defaultEnabled: true
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
controller:
  enabled: true
syncCatalog:
  enabled: false
