global:
  name: consul
  datacenter: dc1
  image: "hashicorp/consul:1.11.1"
  imageEnvoy: "envoyproxy/envoy:v1.19.1"
  acls:
    manageSystemACLs: false
  gossipEncryption:
    autoGenerate: false
  tls:
    enabled: false
    enableAutoEncrypt: true
    verify: true
server:
  replicas: 3
  storageClass: standard
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
ui:
  enabled: true
  service:
    type: "NodePort"
connectInject:
  enabled: true
  default: false
  replicas: 1
  logLevel: "debug"
  k8sAllowNamespaces: ["*"]
  k8sDenyNamespaces: []
  metrics:
    defaultEnabled: true
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
controller:
  enabled: true
syncCatalog:
  enabled: false
client:
  enabled: true
  grpc: true
