apiVersion: v1
kind: ServiceAccount
metadata:
  name: one
---
apiVersion: v1
kind: Service
metadata:
  name: one
spec:
  selector:
    app: one
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: one
spec:
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: one
          image: manedurphy/one
          imagePullPolicy: "Never"
          env:
            - name: TWO_SERVICE_URL
              value: http://two:8081
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
