apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-two
---
apiVersion: v1
kind: Service
metadata:
  name: service-two
spec:
  selector:
    app: service-two
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-two
spec:
  selector:
    matchLabels:
      app: service-two
  template:
    metadata:
      labels:
        app: service-two
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: service-two
          image: manedurphy/service-two
          imagePullPolicy: "Never"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
