apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-one
---
apiVersion: v1
kind: Service
metadata:
  name: service-one
spec:
  selector:
    app: service-one
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-one
spec:
  selector:
    matchLabels:
      app: service-one
  template:
    metadata:
      labels:
        app: service-one
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: service-one
          image: manedurphy/service-one
          imagePullPolicy: "Never"
          env:
            - name: SERVICE_TWO_SERVICE_URL
              value: http://service-two:8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
