apiVersion: v1
kind: ServiceAccount
metadata:
  name: two
---
apiVersion: v1
kind: Service
metadata:
  name: two
spec:
  selector:
    app: two
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: two
spec:
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: two
          image: manedurphy/two
          imagePullPolicy: "Never"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
